//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="results", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int loginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int loginID {
            get {
                return this.loginIDField;
            }
            set {
                if ((this.loginIDField.Equals(value) != true)) {
                    this.loginIDField = value;
                    this.RaisePropertyChanged("loginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAPIServiceRest")]
    public interface IAPIServiceRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIServiceRest/generateAPI", ReplyAction="http://tempuri.org/IAPIServiceRest/generateAPIResponse")]
        ClientWebApplication.ServiceReference1.results generateAPI(string first, string last, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIServiceRest/generateAPI", ReplyAction="http://tempuri.org/IAPIServiceRest/generateAPIResponse")]
        System.Threading.Tasks.Task<ClientWebApplication.ServiceReference1.results> generateAPIAsync(string first, string last, int age);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceRestChannel : ClientWebApplication.ServiceReference1.IAPIServiceRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceRestClient : System.ServiceModel.ClientBase<ClientWebApplication.ServiceReference1.IAPIServiceRest>, ClientWebApplication.ServiceReference1.IAPIServiceRest {
        
        public APIServiceRestClient() {
        }
        
        public APIServiceRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientWebApplication.ServiceReference1.results generateAPI(string first, string last, int age) {
            return base.Channel.generateAPI(first, last, age);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.ServiceReference1.results> generateAPIAsync(string first, string last, int age) {
            return base.Channel.generateAPIAsync(first, last, age);
        }
    }
}
