'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="results", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class results
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private loginIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private passwordField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property loginID() As Integer
            Get
                Return Me.loginIDField
            End Get
            Set
                If (Me.loginIDField.Equals(value) <> true) Then
                    Me.loginIDField = value
                    Me.RaisePropertyChanged("loginID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.passwordField, value) <> true) Then
                    Me.passwordField = value
                    Me.RaisePropertyChanged("password")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IAPIServiceRest")>  _
    Public Interface IAPIServiceRest
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAPIServiceRest/generateAPI", ReplyAction:="http://tempuri.org/IAPIServiceRest/generateAPIResponse")>  _
        Function generateAPI(ByVal first As String, ByVal last As String, ByVal age As Integer) As ServiceReference1.results
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAPIServiceRest/generateAPI", ReplyAction:="http://tempuri.org/IAPIServiceRest/generateAPIResponse")>  _
        Function generateAPIAsync(ByVal first As String, ByVal last As String, ByVal age As Integer) As System.Threading.Tasks.Task(Of ServiceReference1.results)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAPIServiceRestChannel
        Inherits ServiceReference1.IAPIServiceRest, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class APIServiceRestClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IAPIServiceRest)
        Implements ServiceReference1.IAPIServiceRest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generateAPI(ByVal first As String, ByVal last As String, ByVal age As Integer) As ServiceReference1.results Implements ServiceReference1.IAPIServiceRest.generateAPI
            Return MyBase.Channel.generateAPI(first, last, age)
        End Function
        
        Public Function generateAPIAsync(ByVal first As String, ByVal last As String, ByVal age As Integer) As System.Threading.Tasks.Task(Of ServiceReference1.results) Implements ServiceReference1.IAPIServiceRest.generateAPIAsync
            Return MyBase.Channel.generateAPIAsync(first, last, age)
        End Function
    End Class
End Namespace
